name: Build and deploy Python project to Azure Function App

on:
  push:
    branches:
      - Dev         # For Dev environment
      - Stage       # For Staging environment
      - Prod        # For Production environment
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11'               # Python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     

      # Login to Azure with the correct federated identity for each environment
      - name: Login to Azure (Dev)
        if: github.ref == 'refs/heads/Dev' 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Login to Azure (Stage)
        if: github.ref == 'refs/heads/Stage' 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Login to Azure (Prod)
        if: github.ref == 'refs/heads/Prod' 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to the appropriate Azure Function App based on the branch
      - name: 'Deploy to Azure Function App (Dev)'
        if: github.ref == 'refs/heads/Dev'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.APP_NAME_DEV }}
          slot-name: 'Dev'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: 'Deploy to Azure Function App (Stage)'
        if: github.ref == 'refs/heads/Stage'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.APP_NAME_STAGE }}
          slot-name: 'Stage'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          
      - name: 'Deploy to Azure Function App (Prod)'
        if: github.ref == 'refs/heads/Prod'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.APP_NAME_PROD }}
          slot-name: 'Prod'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
